// lib/services/seed_data.dart
// 50 French-English word pairs used to seed the SQLite database on first launch.
// Images use emoji rendered on colored backgrounds (no external assets needed).
// Audio paths are included for future use when audio assets are added.

import '../models/word.dart';

// NOTE: image paths use a special "emoji:" prefix that our custom ImageWidget
// resolves to a generated emoji image — no PNG files needed for the demo.
// In production, replace with real asset paths: "assets/images/dog.png"

const List<Word> kSeedWords = [

  // ── ANIMALS (10 words) ─────────────────────────────────────────────────────
  Word(
    french: 'Chien',
    english: 'Dog',
    image: 'emoji:🐕',
    audio: 'assets/audio/dog.mp3',
    example: 'Le chien court dans le parc. (The dog runs in the park.)',
    category: 'animals',
  ),
  Word(
    french: 'Chat',
    english: 'Cat',
    image: 'emoji:🐈',
    audio: 'assets/audio/cat.mp3',
    example: 'Le chat dort sur le canapé. (The cat sleeps on the sofa.)',
    category: 'animals',
  ),
  Word(
    french: 'Oiseau',
    english: 'Bird',
    image: 'emoji:🐦',
    audio: 'assets/audio/bird.mp3',
    example: "L'oiseau chante le matin. (The bird sings in the morning.)",
    category: 'animals',
  ),
  Word(
    french: 'Cheval',
    english: 'Horse',
    image: 'emoji:🐴',
    audio: 'assets/audio/horse.mp3',
    example: 'Le cheval galope dans le champ. (The horse gallops in the field.)',
    category: 'animals',
  ),
  Word(
    french: 'Lapin',
    english: 'Rabbit',
    image: 'emoji:🐰',
    audio: 'assets/audio/rabbit.mp3',
    example: 'Le lapin mange une carotte. (The rabbit eats a carrot.)',
    category: 'animals',
  ),
  Word(
    french: 'Poisson',
    english: 'Fish',
    image: 'emoji:🐟',
    audio: 'assets/audio/fish.mp3',
    example: 'Le poisson nage dans la mer. (The fish swims in the sea.)',
    category: 'animals',
  ),
  Word(
    french: 'Grenouille',
    english: 'Frog',
    image: 'emoji:🐸',
    audio: 'assets/audio/frog.mp3',
    example: 'La grenouille saute dans l\'étang. (The frog jumps into the pond.)',
    category: 'animals',
  ),
  Word(
    french: 'Éléphant',
    english: 'Elephant',
    image: 'emoji:🐘',
    audio: 'assets/audio/elephant.mp3',
    example: "L'éléphant est très grand. (The elephant is very large.)",
    category: 'animals',
  ),
  Word(
    french: 'Lion',
    english: 'Lion',
    image: 'emoji:🦁',
    audio: 'assets/audio/lion.mp3',
    example: 'Le lion rugit dans la savane. (The lion roars in the savanna.)',
    category: 'animals',
  ),
  Word(
    french: 'Papillon',
    english: 'Butterfly',
    image: 'emoji:🦋',
    audio: 'assets/audio/butterfly.mp3',
    example: 'Le papillon vole de fleur en fleur. (The butterfly flies from flower to flower.)',
    category: 'animals',
  ),

  // ── FOOD (10 words) ─────────────────────────────────────────────────────────
  Word(
    french: 'Pomme',
    english: 'Apple',
    image: 'emoji:🍎',
    audio: 'assets/audio/apple.mp3',
    example: 'Je mange une pomme rouge. (I eat a red apple.)',
    category: 'food',
  ),
  Word(
    french: 'Pain',
    english: 'Bread',
    image: 'emoji:🍞',
    audio: 'assets/audio/bread.mp3',
    example: 'Le pain est frais ce matin. (The bread is fresh this morning.)',
    category: 'food',
  ),
  Word(
    french: 'Fromage',
    english: 'Cheese',
    image: 'emoji:🧀',
    audio: 'assets/audio/cheese.mp3',
    example: 'Le fromage est délicieux. (The cheese is delicious.)',
    category: 'food',
  ),
  Word(
    french: 'Œuf',
    english: 'Egg',
    image: 'emoji:🥚',
    audio: 'assets/audio/egg.mp3',
    example: 'Je mange un œuf le matin. (I eat an egg in the morning.)',
    category: 'food',
  ),
  Word(
    french: 'Lait',
    english: 'Milk',
    image: 'emoji:🥛',
    audio: 'assets/audio/milk.mp3',
    example: 'Le lait est dans le réfrigérateur. (The milk is in the refrigerator.)',
    category: 'food',
  ),
  Word(
    french: 'Orange',
    english: 'Orange',
    image: 'emoji:🍊',
    audio: 'assets/audio/orange.mp3',
    example: "L'orange est sucrée et juteuse. (The orange is sweet and juicy.)",
    category: 'food',
  ),
  Word(
    french: 'Banane',
    english: 'Banana',
    image: 'emoji:🍌',
    audio: 'assets/audio/banana.mp3',
    example: 'La banane est jaune. (The banana is yellow.)',
    category: 'food',
  ),
  Word(
    french: 'Poulet',
    english: 'Chicken',
    image: 'emoji:🍗',
    audio: 'assets/audio/chicken.mp3',
    example: 'Le poulet est cuit au four. (The chicken is baked in the oven.)',
    category: 'food',
  ),
  Word(
    french: 'Soupe',
    english: 'Soup',
    image: 'emoji:🍲',
    audio: 'assets/audio/soup.mp3',
    example: 'La soupe est chaude et bonne. (The soup is hot and tasty.)',
    category: 'food',
  ),
  Word(
    french: 'Gâteau',
    english: 'Cake',
    image: 'emoji:🎂',
    audio: 'assets/audio/cake.mp3',
    example: 'Le gâteau est pour mon anniversaire. (The cake is for my birthday.)',
    category: 'food',
  ),

  // ── HOUSE (10 words) ─────────────────────────────────────────────────────────
  Word(
    french: 'Table',
    english: 'Table',
    image: 'emoji:🪑',
    audio: 'assets/audio/table.mp3',
    example: 'La table est dans la cuisine. (The table is in the kitchen.)',
    category: 'house',
  ),
  Word(
    french: 'Chaise',
    english: 'Chair',
    image: 'emoji:🪑',
    audio: 'assets/audio/chair.mp3',
    example: 'La chaise est confortable. (The chair is comfortable.)',
    category: 'house',
  ),
  Word(
    french: 'Lit',
    english: 'Bed',
    image: 'emoji:🛏',
    audio: 'assets/audio/bed.mp3',
    example: 'Je dors dans mon lit. (I sleep in my bed.)',
    category: 'house',
  ),
  Word(
    french: 'Fenêtre',
    english: 'Window',
    image: 'emoji:🪟',
    audio: 'assets/audio/window.mp3',
    example: 'La fenêtre est ouverte. (The window is open.)',
    category: 'house',
  ),
  Word(
    french: 'Porte',
    english: 'Door',
    image: 'emoji:🚪',
    audio: 'assets/audio/door.mp3',
    example: 'Ferme la porte, s\'il te plaît. (Close the door, please.)',
    category: 'house',
  ),
  Word(
    french: 'Lampe',
    english: 'Lamp',
    image: 'emoji:💡',
    audio: 'assets/audio/lamp.mp3',
    example: 'La lampe éclaire la pièce. (The lamp lights the room.)',
    category: 'house',
  ),
  Word(
    french: 'Réfrigérateur',
    english: 'Refrigerator',
    image: 'emoji:🧊',
    audio: 'assets/audio/fridge.mp3',
    example: 'Le réfrigérateur garde les aliments frais. (The refrigerator keeps food fresh.)',
    category: 'house',
  ),
  Word(
    french: 'Miroir',
    english: 'Mirror',
    image: 'emoji:🪞',
    audio: 'assets/audio/mirror.mp3',
    example: 'Je me regarde dans le miroir. (I look at myself in the mirror.)',
    category: 'house',
  ),
  Word(
    french: 'Canapé',
    english: 'Sofa',
    image: 'emoji:🛋',
    audio: 'assets/audio/sofa.mp3',
    example: 'Nous regardons la télé sur le canapé. (We watch TV on the sofa.)',
    category: 'house',
  ),
  Word(
    french: 'Escalier',
    english: 'Staircase',
    image: 'emoji:🏠',
    audio: 'assets/audio/stairs.mp3',
    example: "L'escalier mène à l'étage. (The staircase leads to the floor above.)",
    category: 'house',
  ),

  // ── SCHOOL (8 words) ─────────────────────────────────────────────────────────
  Word(
    french: 'Livre',
    english: 'Book',
    image: 'emoji:📖',
    audio: 'assets/audio/book.mp3',
    example: 'Je lis un livre intéressant. (I read an interesting book.)',
    category: 'school',
  ),
  Word(
    french: 'Crayon',
    english: 'Pencil',
    image: 'emoji:✏️',
    audio: 'assets/audio/pencil.mp3',
    example: "J'écris avec un crayon. (I write with a pencil.)",
    category: 'school',
  ),
  Word(
    french: 'Cahier',
    english: 'Notebook',
    image: 'emoji:📓',
    audio: 'assets/audio/notebook.mp3',
    example: 'Mon cahier est bleu. (My notebook is blue.)',
    category: 'school',
  ),
  Word(
    french: 'Tableau',
    english: 'Blackboard',
    image: 'emoji:🖊',
    audio: 'assets/audio/blackboard.mp3',
    example: 'Le professeur écrit au tableau. (The teacher writes on the blackboard.)',
    category: 'school',
  ),
  Word(
    french: 'Règle',
    english: 'Ruler',
    image: 'emoji:📏',
    audio: 'assets/audio/ruler.mp3',
    example: 'La règle mesure vingt centimètres. (The ruler measures twenty centimetres.)',
    category: 'school',
  ),
  Word(
    french: 'Sac à dos',
    english: 'Backpack',
    image: 'emoji:🎒',
    audio: 'assets/audio/backpack.mp3',
    example: 'Mon sac à dos est lourd. (My backpack is heavy.)',
    category: 'school',
  ),
  Word(
    french: 'Ciseaux',
    english: 'Scissors',
    image: 'emoji:✂️',
    audio: 'assets/audio/scissors.mp3',
    example: 'Je coupe le papier avec des ciseaux. (I cut the paper with scissors.)',
    category: 'school',
  ),
  Word(
    french: 'Colle',
    english: 'Glue',
    image: 'emoji:📌',
    audio: 'assets/audio/glue.mp3',
    example: 'Je colle les images dans mon cahier. (I glue the pictures in my notebook.)',
    category: 'school',
  ),

  // ── TRANSPORT (6 words) ──────────────────────────────────────────────────────
  Word(
    french: 'Voiture',
    english: 'Car',
    image: 'emoji:🚗',
    audio: 'assets/audio/car.mp3',
    example: 'La voiture roule vite. (The car drives fast.)',
    category: 'transport',
  ),
  Word(
    french: 'Vélo',
    english: 'Bicycle',
    image: 'emoji:🚲',
    audio: 'assets/audio/bicycle.mp3',
    example: 'Je vais à l\'école en vélo. (I go to school by bicycle.)',
    category: 'transport',
  ),
  Word(
    french: 'Train',
    english: 'Train',
    image: 'emoji:🚂',
    audio: 'assets/audio/train.mp3',
    example: 'Le train part à dix heures. (The train leaves at ten o\'clock.)',
    category: 'transport',
  ),
  Word(
    french: 'Avion',
    english: 'Airplane',
    image: 'emoji:✈️',
    audio: 'assets/audio/airplane.mp3',
    example: "L'avion vole très haut. (The airplane flies very high.)",
    category: 'transport',
  ),
  Word(
    french: 'Bateau',
    english: 'Boat',
    image: 'emoji:⛵',
    audio: 'assets/audio/boat.mp3',
    example: 'Le bateau navigue sur la mer. (The boat sails on the sea.)',
    category: 'transport',
  ),
  Word(
    french: 'Bus',
    english: 'Bus',
    image: 'emoji:🚌',
    audio: 'assets/audio/bus.mp3',
    example: 'Je prends le bus chaque matin. (I take the bus every morning.)',
    category: 'transport',
  ),

  // ── NATURE (6 words) ─────────────────────────────────────────────────────────
  Word(
    french: 'Arbre',
    english: 'Tree',
    image: 'emoji:🌳',
    audio: 'assets/audio/tree.mp3',
    example: "L'arbre est très grand. (The tree is very tall.)",
    category: 'nature',
  ),
  Word(
    french: 'Fleur',
    english: 'Flower',
    image: 'emoji:🌸',
    audio: 'assets/audio/flower.mp3',
    example: 'La fleur sent bon. (The flower smells nice.)',
    category: 'nature',
  ),
  Word(
    french: 'Soleil',
    english: 'Sun',
    image: 'emoji:☀️',
    audio: 'assets/audio/sun.mp3',
    example: 'Le soleil brille aujourd\'hui. (The sun is shining today.)',
    category: 'nature',
  ),
  Word(
    french: 'Montagne',
    english: 'Mountain',
    image: 'emoji:⛰',
    audio: 'assets/audio/mountain.mp3',
    example: 'La montagne est couverte de neige. (The mountain is covered in snow.)',
    category: 'nature',
  ),
  Word(
    french: 'Rivière',
    english: 'River',
    image: 'emoji:🏞',
    audio: 'assets/audio/river.mp3',
    example: 'La rivière coule doucement. (The river flows gently.)',
    category: 'nature',
  ),
  Word(
    french: 'Nuage',
    english: 'Cloud',
    image: 'emoji:☁️',
    audio: 'assets/audio/cloud.mp3',
    example: 'Le nuage cache le soleil. (The cloud hides the sun.)',
    category: 'nature',
  ),
];
